---
- hosts: all
  gather_facts: no
  serial: 1
  tasks:
    - name: Check for missing updates
      win_updates:
        category_names:
          [
            "SecurityUpdates",
            "CriticalUpdates",
            "UpdateRollups",
            "Updates",
            "DefinitionUpdates",
          ]
        state: searched
        log_path: C:\ansible_wu.txt
        no_log: True
      register: update_count
