- hosts: all
  gather_facts: no
  tasks:
    # pserver
    - name: nts1
      win_hosts:
        state: present
        canonical_name: nts1.praxis.local
        ip_address: 100.100.100.110
        action: add
        aliases:
          - nts1
          - pserver
    # Thin clients
    - name: anmeldung1
      win_hosts:
        state: present
        canonical_name: anmeldung1.praxis.local
        ip_address: 100.100.100.151
        action: add
        aliases:
          - anmeldung1
    - name: anmeldung2
      win_hosts:
        state: present
        canonical_name: anmeldung2.praxis.local
        ip_address: 100.100.100.152
        action: add
        aliases:
          - anmeldung2
    - name: uzimmer1
      win_hosts:
        state: present
        canonical_name: uzimmer1.praxis.local
        ip_address: 100.100.100.153
        action: add
        aliases:
          - uzimmer1
    - name: uzimmer2
      win_hosts:
        state: present
        canonical_name: uzimmer2.praxis.local
        ip_address: 100.100.100.154
        action: add
        aliases:
          - uzimmer2
    # Virtual clients
    - name: anmeldungv1
      win_hosts:
        state: present
        canonical_name: anmeldungv1.praxis.local
        ip_address: 100.100.100.11
        action: add
        aliases:
          - anmeldungv1
    - name: anmeldungv2
      win_hosts:
        state: present
        canonical_name: anmeldungv2.praxis.local
        ip_address: 100.100.100.16
        action: add
        aliases:
          - anmeldungv2
    - name: uzimmerv1
      win_hosts:
        state: present
        canonical_name: uzimmerv1.praxis.local
        ip_address: 100.100.100.13
        action: add
        aliases:
          - uzimmerv1
    - name: uzimmerv2
      win_hosts:
        state: present
        canonical_name: uzimmerv2.praxis.local
        ip_address: 100.100.100.14
        action: add
        aliases:
          - uzimmerv2
    - name: katrinv1
      win_hosts:
        state: present
        canonical_name: katrinv1.praxis.local
        ip_address: 100.100.100.20
        action: add
        aliases:
          - katrinv1
    # Laptops
    - name: gesichtsfeld1
      win_hosts:
        state: present
        canonical_name: gesichtsfeld1.praxis.local
        ip_address: 100.100.100.155
        action: add
        aliases:
          - gesichtsfeld1
    - name: gesichtsfeld2
      win_hosts:
        state: present
        canonical_name: gesichtsfeld2.praxis.local
        ip_address: 192.168.101.156
        action: add
        aliases:
          - gesichtsfeld2
    - name: he
      win_hosts:
        state: present
        canonical_name: he.praxis.local
        ip_address: 100.100.100.157
        action: add
        aliases:
          - he
    - name: kueche
      win_hosts:
        state: present
        canonical_name: kueche.praxis.local
        ip_address: 100.100.100.158
        action: add
        aliases:
          - kueche
      # Printer
    - name: printer1
      win_hosts:
        state: present
        canonical_name: printer1.praxis.local
        ip_address: 100.100.100.51
        action: add
        aliases:
          - printer1
    - name: printer2
      win_hosts:
        state: present
        canonical_name: printer2.praxis.local
        ip_address: 100.100.100.52
        action: add
        aliases:
          - printer2
    - name: hl2030
      win_hosts:
        state: present
        canonical_name: hl2030.praxis.local
        ip_address: 100.100.100.51
        action: add
        aliases:
          - hl2030
    # Card readers
    # card1 has been used at anmeldungv1 in the past. It's not used anymore.
    - name: card1
      win_hosts:
        state: present
        canonical_name: card1.praxis.local
        ip_address: 100.100.100.61
        action: add
        aliases:
          - card1
    - name: card2
      win_hosts:
        state: present
        canonical_name: card2.praxis.local
        ip_address: 100.100.100.62
        action: add
        aliases:
          - card2
    # TI devices
    - name: orga_1
      win_hosts:
        state: present
        canonical_name: orga_1.praxis.local
        ip_address: 192.168.101.81
        action: add
        aliases:
          - orga_1
    - name: kocobox
      win_hosts:
        state: present
        canonical_name: kocobox.praxis.local
        ip_address: 192.168.101.250
        action: add
        aliases:
          - kocobox
